FROM debian:buster-slim
#FROM python:3.8.2-slim-buster
# basics
RUN apt-get update
RUN apt-get install libopenblas-dev libopenmpi-dev python3-setuptools python3-pip libjpeg-dev zlib1g-dev ffmpeg libsm6 libxext6  cmake -y

# necessary packages before the requirements.txt
RUN pip3 install Cython numpy setuptools

# update pip
RUN pip3 install --upgrade pip

ADD client/requirements.txt .
RUN pip3 install -r requirements.txt

RUN mkdir /app

ADD client/src /app/src/
ADD utils /app/utils
ADD models /app/models
ADD client/main.py /app/main.py

ENV GIT_PYTHON_REFRESH=quiet

WORKDIR /app

